#define PASTE_1(...) __VA_ARGS__
#define PASTE_2(...)  PASTE_1(__VA_ARGS__)  PASTE_1(__VA_ARGS__)
#define PASTE_3(...)  PASTE_2(__VA_ARGS__)  PASTE_1(__VA_ARGS__)
#define PASTE_4(...)  PASTE_2(__VA_ARGS__)  PASTE_2(__VA_ARGS__)
#define PASTE_5(...)  PASTE_4(__VA_ARGS__)  PASTE_1(__VA_ARGS__)
#define PASTE_6(...)  PASTE_4(__VA_ARGS__)  PASTE_2(__VA_ARGS__)
#define PASTE_7(...)  PASTE_4(__VA_ARGS__)  PASTE_3(__VA_ARGS__)
#define PASTE_8(...)  PASTE_4(__VA_ARGS__)  PASTE_4(__VA_ARGS__)
#define PASTE_9(...)  PASTE_8(__VA_ARGS__)  PASTE_1(__VA_ARGS__)
#define PASTE_10(...) PASTE_8(__VA_ARGS__)  PASTE_2(__VA_ARGS__)
#define PASTE_11(...) PASTE_8(__VA_ARGS__)  PASTE_3(__VA_ARGS__)
#define PASTE_12(...) PASTE_8(__VA_ARGS__)  PASTE_4(__VA_ARGS__)
#define PASTE_13(...) PASTE_8(__VA_ARGS__)  PASTE_5(__VA_ARGS__)
#define PASTE_14(...) PASTE_8(__VA_ARGS__)  PASTE_6(__VA_ARGS__)
#define PASTE_15(...) PASTE_8(__VA_ARGS__)  PASTE_7(__VA_ARGS__)
#define PASTE_16(...) PASTE_8(__VA_ARGS__)  PASTE_8(__VA_ARGS__)
#define PASTE_17(...) PASTE_16(__VA_ARGS__) PASTE_1(__VA_ARGS__)
#define PASTE_18(...) PASTE_16(__VA_ARGS__) PASTE_2(__VA_ARGS__)
#define PASTE_19(...) PASTE_16(__VA_ARGS__) PASTE_3(__VA_ARGS__)
#define PASTE_20(...) PASTE_16(__VA_ARGS__) PASTE_4(__VA_ARGS__)
#define PASTE_21(...) PASTE_16(__VA_ARGS__) PASTE_5(__VA_ARGS__)
#define PASTE_22(...) PASTE_16(__VA_ARGS__) PASTE_6(__VA_ARGS__)
#define PASTE_23(...) PASTE_16(__VA_ARGS__) PASTE_7(__VA_ARGS__)
#define PASTE_24(...) PASTE_16(__VA_ARGS__) PASTE_8(__VA_ARGS__)
#define PASTE_25(...) PASTE_16(__VA_ARGS__) PASTE_9(__VA_ARGS__)
#define PASTE_26(...) PASTE_16(__VA_ARGS__) PASTE_10(__VA_ARGS__)
#define PASTE_27(...) PASTE_16(__VA_ARGS__) PASTE_11(__VA_ARGS__)
#define PASTE_28(...) PASTE_16(__VA_ARGS__) PASTE_12(__VA_ARGS__)
#define PASTE_29(...) PASTE_16(__VA_ARGS__) PASTE_13(__VA_ARGS__)
#define PASTE_30(...) PASTE_16(__VA_ARGS__) PASTE_14(__VA_ARGS__)
#define PASTE_31(...) PASTE_16(__VA_ARGS__) PASTE_15(__VA_ARGS__)
#define PASTE_32(...) PASTE_16(__VA_ARGS__) PASTE_16(__VA_ARGS__)

#define ACG_EMPTY()
#define ACG_DEFER(ID) ID ACG_EMPTY() // (ARGS)
#define ACG_EVAL(...) __VA_ARGS__
